sudo: required
services:
  - docker

before_install:
  - docker build -t jkirito/docker-react2 -f Dockerfile.dev .

script:
  - docker run jkirito/docker-react2 yarn run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-333951462427'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
